import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'

dotenv.config({ path: '.env.local' })

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

const supabase = createClient(supabaseUrl, supabaseServiceKey)

// Seed data for furniture products
// Using real product-like data with placeholder affiliate URLs
const products = [
  // === SOFAS ===
  {
    name: 'Sven Charme Tan Sofa',
    description: 'Mid-century modern leather sofa with solid wood frame and high-density foam cushions.',
    brand: 'Article',
    retailer: 'article',
    price: 1699,
    category: 'sofa',
    subcategory: 'leather_sofa',
    room_type: ['living_room'],
    styles: ['mid-century', 'modern'],
    colors: ['brown', 'tan'],
    materials: ['leather', 'wood'],
    width: 88,
    height: 34,
    depth: 38,
    image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    product_url: 'https://www.article.com/product/sven-charme-tan-sofa',
    rating: 4.8,
    review_count: 2341,
  },
  {
    name: 'Cloud Modular Sectional',
    description: 'Deep, plush modular sofa with feather-blend cushions. Ultimate comfort for lounging.',
    brand: 'Restoration Hardware',
    retailer: 'wayfair',
    price: 2499,
    category: 'sofa',
    subcategory: 'sectional',
    room_type: ['living_room'],
    styles: ['modern', 'contemporary'],
    colors: ['gray', 'beige'],
    materials: ['fabric', 'wood'],
    width: 120,
    height: 32,
    depth: 45,
    image_url: 'https://images.unsplash.com/photo-1550581190-9c1c48d21d6c?w=800',
    product_url: 'https://www.wayfair.com/cloud-sectional',
    rating: 4.7,
    review_count: 1892,
  },
  {
    name: 'Stockholm Velvet Sofa',
    description: 'Scandinavian-inspired velvet sofa with clean lines and solid oak legs.',
    brand: 'IKEA',
    retailer: 'ikea',
    price: 899,
    category: 'sofa',
    subcategory: 'velvet_sofa',
    room_type: ['living_room'],
    styles: ['scandinavian', 'modern'],
    colors: ['green', 'blue', 'gray'],
    materials: ['velvet', 'wood'],
    width: 82,
    height: 32,
    depth: 35,
    image_url: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800',
    product_url: 'https://www.ikea.com/stockholm-sofa',
    rating: 4.5,
    review_count: 3421,
  },
  {
    name: 'Timber Charme Chocolat Sofa',
    description: 'Modern leather sofa with solid walnut frame and premium Italian leather.',
    brand: 'Article',
    retailer: 'article',
    price: 1899,
    category: 'sofa',
    subcategory: 'leather_sofa',
    room_type: ['living_room', 'office'],
    styles: ['modern', 'industrial'],
    colors: ['brown'],
    materials: ['leather', 'wood'],
    width: 90,
    height: 33,
    depth: 36,
    image_url: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800',
    product_url: 'https://www.article.com/timber-sofa',
    rating: 4.9,
    review_count: 1567,
  },

  // === CHAIRS ===
  {
    name: 'Eames Lounge Chair Replica',
    description: 'Iconic mid-century lounge chair with ottoman. Premium leather and molded plywood.',
    brand: 'Manhattan Home Design',
    retailer: 'wayfair',
    price: 1299,
    category: 'chair',
    subcategory: 'lounge_chair',
    room_type: ['living_room', 'office'],
    styles: ['mid-century', 'modern'],
    colors: ['black', 'brown', 'white'],
    materials: ['leather', 'wood'],
    width: 33,
    height: 32,
    depth: 32,
    image_url: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800',
    product_url: 'https://www.wayfair.com/eames-lounge',
    rating: 4.6,
    review_count: 892,
  },
  {
    name: 'Womb Chair',
    description: 'Sculptural accent chair with organic curves. Upholstered in boucle fabric.',
    brand: 'Knoll',
    retailer: 'wayfair',
    price: 899,
    category: 'chair',
    subcategory: 'accent_chair',
    room_type: ['living_room', 'bedroom'],
    styles: ['mid-century', 'modern'],
    colors: ['white', 'gray', 'orange'],
    materials: ['fabric', 'metal'],
    width: 38,
    height: 35,
    depth: 34,
    image_url: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800',
    product_url: 'https://www.wayfair.com/womb-chair',
    rating: 4.7,
    review_count: 543,
  },
  {
    name: 'POÄNG Armchair',
    description: 'Classic bentwood armchair with cushioned seat. Durable and comfortable.',
    brand: 'IKEA',
    retailer: 'ikea',
    price: 149,
    category: 'chair',
    subcategory: 'armchair',
    room_type: ['living_room', 'bedroom', 'office'],
    styles: ['scandinavian', 'minimalist'],
    colors: ['beige', 'gray', 'black'],
    materials: ['fabric', 'wood'],
    width: 27,
    height: 39,
    depth: 32,
    image_url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
    product_url: 'https://www.ikea.com/poang',
    rating: 4.4,
    review_count: 8923,
  },
  {
    name: 'Accent Velvet Armchair',
    description: 'Modern velvet armchair with brass legs. Statement piece for any room.',
    brand: 'West Elm',
    retailer: 'west_elm',
    price: 599,
    category: 'chair',
    subcategory: 'accent_chair',
    room_type: ['living_room', 'bedroom'],
    styles: ['modern', 'bohemian'],
    colors: ['green', 'pink', 'blue', 'yellow'],
    materials: ['velvet', 'metal'],
    width: 30,
    height: 32,
    depth: 30,
    image_url: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800',
    product_url: 'https://www.westelm.com/velvet-armchair',
    rating: 4.5,
    review_count: 672,
  },

  // === TABLES ===
  {
    name: 'Mid-Century Coffee Table',
    description: 'Solid walnut coffee table with tapered legs and lower shelf.',
    brand: 'West Elm',
    retailer: 'west_elm',
    price: 449,
    category: 'table',
    subcategory: 'coffee_table',
    room_type: ['living_room'],
    styles: ['mid-century', 'modern'],
    colors: ['brown', 'walnut'],
    materials: ['wood'],
    width: 48,
    height: 16,
    depth: 24,
    image_url: 'https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=800',
    product_url: 'https://www.westelm.com/mid-century-coffee-table',
    rating: 4.6,
    review_count: 1234,
  },
  {
    name: 'LACK Coffee Table',
    description: 'Simple, minimalist coffee table. Lightweight and affordable.',
    brand: 'IKEA',
    retailer: 'ikea',
    price: 29,
    category: 'table',
    subcategory: 'coffee_table',
    room_type: ['living_room'],
    styles: ['minimalist', 'modern'],
    colors: ['white', 'black', 'oak'],
    materials: ['wood'],
    width: 46,
    height: 18,
    depth: 30,
    image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    product_url: 'https://www.ikea.com/lack-coffee-table',
    rating: 4.2,
    review_count: 15234,
  },
  {
    name: 'Marble Round Side Table',
    description: 'Elegant marble-top side table with gold metal base.',
    brand: 'CB2',
    retailer: 'cb2',
    price: 249,
    category: 'table',
    subcategory: 'side_table',
    room_type: ['living_room', 'bedroom'],
    styles: ['modern', 'contemporary'],
    colors: ['white', 'gold'],
    materials: ['marble', 'metal'],
    width: 16,
    height: 22,
    depth: 16,
    image_url: 'https://images.unsplash.com/photo-1499933374294-4584851497cc?w=800',
    product_url: 'https://www.cb2.com/marble-side-table',
    rating: 4.7,
    review_count: 432,
  },
  {
    name: 'Industrial Console Table',
    description: 'Reclaimed wood console table with black metal frame.',
    brand: 'Pottery Barn',
    retailer: 'pottery_barn',
    price: 699,
    category: 'table',
    subcategory: 'console_table',
    room_type: ['living_room', 'dining_room'],
    styles: ['industrial', 'farmhouse'],
    colors: ['brown', 'black'],
    materials: ['wood', 'metal'],
    width: 54,
    height: 30,
    depth: 14,
    image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    product_url: 'https://www.potterybarn.com/console-table',
    rating: 4.5,
    review_count: 287,
  },

  // === RUGS ===
  {
    name: 'Moroccan Shag Area Rug',
    description: 'Plush shag rug with geometric Moroccan pattern. Hand-tufted wool.',
    brand: 'Rugs USA',
    retailer: 'wayfair',
    price: 299,
    category: 'rug',
    subcategory: 'area_rug',
    room_type: ['living_room', 'bedroom'],
    styles: ['bohemian', 'modern'],
    colors: ['white', 'cream', 'gray'],
    materials: ['wool'],
    width: 96,
    height: 0.5,
    depth: 120,
    image_url: 'https://images.unsplash.com/photo-1600166898405-da9535204843?w=800',
    product_url: 'https://www.wayfair.com/moroccan-shag-rug',
    rating: 4.5,
    review_count: 3421,
  },
  {
    name: 'Persian Vintage Rug',
    description: 'Machine-woven vintage-style Persian rug. Distressed finish.',
    brand: 'Loloi',
    retailer: 'wayfair',
    price: 199,
    category: 'rug',
    subcategory: 'area_rug',
    room_type: ['living_room', 'dining_room', 'bedroom'],
    styles: ['traditional', 'bohemian'],
    colors: ['blue', 'red', 'beige'],
    materials: ['polypropylene'],
    width: 96,
    height: 0.25,
    depth: 120,
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    product_url: 'https://www.wayfair.com/persian-rug',
    rating: 4.6,
    review_count: 2134,
  },
  {
    name: 'Jute Natural Fiber Rug',
    description: 'Hand-woven natural jute rug. Eco-friendly and durable.',
    brand: 'Safavieh',
    retailer: 'amazon',
    price: 149,
    category: 'rug',
    subcategory: 'area_rug',
    room_type: ['living_room', 'dining_room'],
    styles: ['coastal', 'farmhouse', 'bohemian'],
    colors: ['beige', 'natural'],
    materials: ['jute'],
    width: 96,
    height: 0.5,
    depth: 120,
    image_url: 'https://images.unsplash.com/photo-1600166898405-da9535204843?w=800',
    product_url: 'https://www.amazon.com/jute-rug',
    rating: 4.3,
    review_count: 5678,
  },

  // === LAMPS ===
  {
    name: 'Arc Floor Lamp',
    description: 'Modern arched floor lamp with marble base and adjustable arm.',
    brand: 'West Elm',
    retailer: 'west_elm',
    price: 349,
    category: 'lamp',
    subcategory: 'floor_lamp',
    room_type: ['living_room', 'bedroom', 'office'],
    styles: ['modern', 'mid-century'],
    colors: ['brass', 'black', 'white'],
    materials: ['metal', 'marble'],
    width: 12,
    height: 72,
    depth: 40,
    image_url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800',
    product_url: 'https://www.westelm.com/arc-floor-lamp',
    rating: 4.7,
    review_count: 892,
  },
  {
    name: 'Tripod Floor Lamp',
    description: 'Scandinavian tripod floor lamp with fabric drum shade.',
    brand: 'IKEA',
    retailer: 'ikea',
    price: 79,
    category: 'lamp',
    subcategory: 'floor_lamp',
    room_type: ['living_room', 'bedroom'],
    styles: ['scandinavian', 'minimalist'],
    colors: ['white', 'gray', 'natural'],
    materials: ['wood', 'fabric'],
    width: 20,
    height: 60,
    depth: 20,
    image_url: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800',
    product_url: 'https://www.ikea.com/tripod-lamp',
    rating: 4.4,
    review_count: 2341,
  },
  {
    name: 'Ceramic Table Lamp',
    description: 'Handmade ceramic table lamp with linen shade. Unique textured finish.',
    brand: 'Pottery Barn',
    retailer: 'pottery_barn',
    price: 199,
    category: 'lamp',
    subcategory: 'table_lamp',
    room_type: ['living_room', 'bedroom'],
    styles: ['coastal', 'traditional', 'farmhouse'],
    colors: ['white', 'blue', 'green'],
    materials: ['ceramic', 'fabric'],
    width: 15,
    height: 26,
    depth: 15,
    image_url: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=800',
    product_url: 'https://www.potterybarn.com/ceramic-lamp',
    rating: 4.6,
    review_count: 567,
  },

  // === PLANTS ===
  {
    name: 'Fiddle Leaf Fig Tree',
    description: 'Artificial fiddle leaf fig tree, 6ft tall. Lifelike silk leaves.',
    brand: 'Nearly Natural',
    retailer: 'amazon',
    price: 129,
    category: 'plant',
    subcategory: 'artificial_tree',
    room_type: ['living_room', 'office', 'bedroom'],
    styles: ['modern', 'bohemian', 'scandinavian'],
    colors: ['green'],
    materials: ['silk', 'plastic'],
    width: 24,
    height: 72,
    depth: 24,
    image_url: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=800',
    product_url: 'https://www.amazon.com/fiddle-leaf-fig',
    rating: 4.5,
    review_count: 4532,
  },
  {
    name: 'Snake Plant in Pot',
    description: 'Real snake plant (Sansevieria) in ceramic pot. Low maintenance.',
    brand: 'The Sill',
    retailer: 'amazon',
    price: 65,
    category: 'plant',
    subcategory: 'potted_plant',
    room_type: ['living_room', 'office', 'bedroom', 'bathroom'],
    styles: ['modern', 'minimalist', 'scandinavian'],
    colors: ['green'],
    materials: ['live_plant', 'ceramic'],
    width: 8,
    height: 24,
    depth: 8,
    image_url: 'https://images.unsplash.com/photo-1593482892290-f54927ae1bb6?w=800',
    product_url: 'https://www.amazon.com/snake-plant',
    rating: 4.7,
    review_count: 2341,
  },
  {
    name: 'Monstera Deliciosa',
    description: 'Artificial monstera plant with realistic split leaves. 4ft tall.',
    brand: 'Nearly Natural',
    retailer: 'wayfair',
    price: 89,
    category: 'plant',
    subcategory: 'artificial_plant',
    room_type: ['living_room', 'office'],
    styles: ['bohemian', 'modern', 'contemporary'],
    colors: ['green'],
    materials: ['silk', 'plastic'],
    width: 30,
    height: 48,
    depth: 30,
    image_url: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=800',
    product_url: 'https://www.wayfair.com/monstera',
    rating: 4.4,
    review_count: 1234,
  },

  // === DECOR ===
  {
    name: 'Decorative Throw Pillows Set',
    description: 'Set of 4 textured throw pillows. Mix of solid and patterned.',
    brand: 'Threshold',
    retailer: 'target',
    price: 49,
    category: 'decor',
    subcategory: 'pillows',
    room_type: ['living_room', 'bedroom'],
    styles: ['modern', 'bohemian', 'farmhouse'],
    colors: ['beige', 'cream', 'gray', 'blue'],
    materials: ['cotton', 'linen'],
    width: 18,
    height: 18,
    depth: 4,
    image_url: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800',
    product_url: 'https://www.target.com/throw-pillows',
    rating: 4.5,
    review_count: 3421,
  },
  {
    name: 'Chunky Knit Throw Blanket',
    description: 'Hand-knitted chunky throw blanket. 100% acrylic, machine washable.',
    brand: 'Bearaby',
    retailer: 'amazon',
    price: 89,
    category: 'decor',
    subcategory: 'blanket',
    room_type: ['living_room', 'bedroom'],
    styles: ['scandinavian', 'modern', 'coastal'],
    colors: ['white', 'gray', 'beige', 'pink'],
    materials: ['acrylic'],
    width: 50,
    height: 60,
    depth: 2,
    image_url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
    product_url: 'https://www.amazon.com/chunky-throw',
    rating: 4.7,
    review_count: 5678,
  },
  {
    name: 'Abstract Wall Art Set',
    description: 'Set of 3 framed abstract prints. Modern minimalist design.',
    brand: 'Deny Designs',
    retailer: 'wayfair',
    price: 149,
    category: 'art',
    subcategory: 'wall_art',
    room_type: ['living_room', 'bedroom', 'office'],
    styles: ['modern', 'minimalist', 'contemporary'],
    colors: ['neutral', 'beige', 'black', 'white'],
    materials: ['paper', 'wood_frame'],
    width: 24,
    height: 36,
    depth: 1,
    image_url: 'https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=800',
    product_url: 'https://www.wayfair.com/abstract-art',
    rating: 4.6,
    review_count: 892,
  },
  {
    name: 'Round Decorative Mirror',
    description: 'Large round mirror with thin gold frame. 36" diameter.',
    brand: 'West Elm',
    retailer: 'west_elm',
    price: 299,
    category: 'mirror',
    subcategory: 'wall_mirror',
    room_type: ['living_room', 'bedroom', 'bathroom'],
    styles: ['modern', 'minimalist', 'contemporary'],
    colors: ['gold', 'black', 'brass'],
    materials: ['glass', 'metal'],
    width: 36,
    height: 36,
    depth: 1,
    image_url: 'https://images.unsplash.com/photo-1618220179428-22790b461013?w=800',
    product_url: 'https://www.westelm.com/round-mirror',
    rating: 4.8,
    review_count: 1234,
  },

  // === STORAGE ===
  {
    name: 'KALLAX Shelf Unit',
    description: 'Versatile cube storage unit. Can be used vertically or horizontally.',
    brand: 'IKEA',
    retailer: 'ikea',
    price: 69,
    category: 'storage',
    subcategory: 'bookshelf',
    room_type: ['living_room', 'office', 'bedroom'],
    styles: ['modern', 'minimalist', 'scandinavian'],
    colors: ['white', 'black', 'oak'],
    materials: ['wood'],
    width: 57,
    height: 57,
    depth: 15,
    image_url: 'https://images.unsplash.com/photo-1594620302200-9a762244a156?w=800',
    product_url: 'https://www.ikea.com/kallax',
    rating: 4.6,
    review_count: 12345,
  },
  {
    name: 'Media Console',
    description: 'Mid-century modern media console with sliding doors. Solid wood.',
    brand: 'Article',
    retailer: 'article',
    price: 799,
    category: 'storage',
    subcategory: 'media_console',
    room_type: ['living_room'],
    styles: ['mid-century', 'modern'],
    colors: ['walnut', 'oak', 'white'],
    materials: ['wood'],
    width: 63,
    height: 24,
    depth: 18,
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    product_url: 'https://www.article.com/media-console',
    rating: 4.7,
    review_count: 567,
  },
]

async function seedProducts() {
  console.log('🌱 Seeding products database...')
  console.log(`📦 Total products to insert: ${products.length}`)

  // Add affiliate URLs (placeholder pattern)
  const productsWithAffiliates = products.map((p) => ({
    ...p,
    affiliate_url: `${p.product_url}?ref=renderai&utm_source=renderai`,
    affiliate_code: 'renderai',
    in_stock: true,
    currency: 'USD',
  }))

  // Insert in batches
  const batchSize = 10
  let inserted = 0

  for (let i = 0; i < productsWithAffiliates.length; i += batchSize) {
    const batch = productsWithAffiliates.slice(i, i + batchSize)

    const { error } = await supabase.from('products').insert(batch)

    if (error) {
      console.error(`❌ Error inserting batch ${i / batchSize + 1}:`, error.message)
    } else {
      inserted += batch.length
      console.log(`✅ Inserted batch ${i / batchSize + 1} (${inserted}/${products.length})`)
    }
  }

  console.log(`\n🎉 Seeding complete! Inserted ${inserted} products.`)

  // Verify
  const { count } = await supabase.from('products').select('*', { count: 'exact', head: true })
  console.log(`📊 Total products in database: ${count}`)
}

// Run the seed
seedProducts().catch(console.error)
